[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "thermodrift"
version = "2023.12.0"
authors = [
    {name = "Gunnar Voet", email = 'gvoet@ucsd.edu'},
]
description = "Moored thermistor processing"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["physical oceanography"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Oceanography",
    ]
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.26.2",
    "xarray>=2023.12.0",
    "matplotlib>=3.8.2",
    "gsw>=3.6.17",
    "rbrmoored @ file:///Users/gunnar/Projects/python/rbrmoored",
    "sbemoored @ file:///Users/gunnar/Projects/python/sbemoored",
    "pyyaml>=6.0.1",
    "python-box>=7.1.1",
    "openpyxl>=3.1.2",
]

[project.urls]
# Homepage = "https://example.com"
# Documentation = "https://readthedocs.org"
Repository = "https://github.com/gunnarvoet/thermodrift.git"
Issues = "https://github.com/gunnarvoet/thermodrift/issues"
Changelog = "https://github.com/gunnarvoet/thermodrift/blob/main/HISTORY.md"

[tool.pytest.ini_options]
# in general, do not place a `__init__.py` in your tests
# options are explained here:
# https://learn.scientific-python.org/development/guides/pytest/
# minversion = "6.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config", "--import-mode=importlib"]
xfail_strict = true
# filterwarnings = ["error"]
# log_cli_level = "info"
testpaths = ["tests"]
filterwarnings = [
    "error",
    # note the use of single quote below to denote "raw" strings in TOML
    'ignore:invalid escape sequence:DeprecationWarning',
]

[tool.pdm]
package-type = "library"
